"""مخططات Marshmallow: شكل الطلب والردّ والتحقّق. لا منطق أعمال ولا وصول للقاعدة."""

from .audit import ResetPinSchema
from .audit_log import AuditLogSchema
from .auth import LoginSchema, SessionSchema
from .daily_question import (
    CreateQuestionSchema,
    QuestionRefSchema,
    QuestionsListSchema,
    UpdateQuestionSchema,
)
from .engagement import (
    AdminNotesListSchema,
    AnsweredSchema,
    AnswerSchema,
    ChooseWeekPilotSchema,
    ChosenWeekPilotSchema,
    MarkedNoteSchema,
    MarkNoteReadSchema,
    SubmitNoteSchema,
    TodayQuestionSchema,
    WeekPilotSchema,
)
from .entry import (
    AttendanceStatusSchema,
    RecordAttendanceSchema,
    RecordedAttendanceSchema,
    UndoneAttendanceSchema,
)
from .fuel import (
    ActivitiesListSchema,
    AssessedSchema,
    AssessSchema,
    AssignTeamSchema,
    CreateActivitySchema,
    CreatedActivitySchema,
    FuelWeekSchema,
    StationSchema,
    WeekScoresSchema,
    WeekTaskRefSchema,
)
from .me import DeckSchema, EventsSchema
from .paste import (
    PasteCommitResultSchema,
    PastePreviewRowSchema,
    PastePreviewSchema,
    PastePreviewTotalsSchema,
    PasteRowResultSchema,
    RasdLatestImportSchema,
)
from .quran import (
    AddedQuranEntrySchema,
    AddQuranEntrySchema,
    AmendedEventSchema,
    AmendEventSchema,
    QuranEventsListSchema,
    ReversedEventSchema,
    ReverseEventSchema,
    StudentsListSchema,
)
from .reading import (
    AdminEntryResultSchema,
    AdminTahdirEntrySchema,
    ApproveSchema,
    MyReadingsSchema,
    OrgTahdirReportSchema,
    OrgTahdirTotalsSchema,
    QueueSchema,
    RejectSchema,
    ReviewResultsSchema,
    SubmitReadingSchema,
    SubmitTahdirSchema,
    SubmittedSchema,
    TahdirReportSchema,
)
from .report import ReportSchema
from .roster import (
    ActiveSetSchema,
    BulkCreatedSchema,
    BulkCreateStudentsSchema,
    CreateStudentSchema,
    IssuedStudentSchema,
    RoleSetSchema,
    RosterListSchema,
    SetActiveSchema,
    SetRoleSchema,
)
from .rules_admin import (
    AppendThresholdSchema,
    CreateWeightVersionSchema,
    SaveThresholdsSchema,
    ThresholdsPreviewSchema,
    ThresholdsSchema,
    WeightsSchema,
    WeightVersionIdSchema,
)
from .standings import FormationSchema, PilotsBoardSchema, TeamsBoardSchema
from .teams import (
    ArchivedTeamSchema,
    ArchiveTeamSchema,
    CreatedTeamSchema,
    CreateTeamSchema,
    TeamsListSchema,
    TransferMemberSchema,
    TransferredMemberSchema,
)

__all__ = [
    "ActiveSetSchema",
    "ActivitiesListSchema",
    "AddQuranEntrySchema",
    "AddedQuranEntrySchema",
    "AdminEntryResultSchema",
    "AdminNotesListSchema",
    "AdminTahdirEntrySchema",
    "AmendEventSchema",
    "AmendedEventSchema",
    "AnswerSchema",
    "AnsweredSchema",
    "AppendThresholdSchema",
    "ApproveSchema",
    "ArchiveTeamSchema",
    "ArchivedTeamSchema",
    "AssessSchema",
    "AssessedSchema",
    "AssignTeamSchema",
    "AttendanceStatusSchema",
    "AuditLogSchema",
    "BulkCreateStudentsSchema",
    "BulkCreatedSchema",
    "ChooseWeekPilotSchema",
    "ChosenWeekPilotSchema",
    "CreateActivitySchema",
    "CreateQuestionSchema",
    "CreateStudentSchema",
    "CreateTeamSchema",
    "CreateWeightVersionSchema",
    "CreatedActivitySchema",
    "CreatedTeamSchema",
    "DeckSchema",
    "EventsSchema",
    "FormationSchema",
    "FuelWeekSchema",
    "IssuedStudentSchema",
    "LoginSchema",
    "MarkNoteReadSchema",
    "MarkedNoteSchema",
    "MyReadingsSchema",
    "OrgTahdirReportSchema",
    "OrgTahdirTotalsSchema",
    "PasteCommitResultSchema",
    "PastePreviewRowSchema",
    "PastePreviewSchema",
    "PastePreviewTotalsSchema",
    "PasteRowResultSchema",
    "PilotsBoardSchema",
    "QuestionRefSchema",
    "QuestionsListSchema",
    "QueueSchema",
    "QuranEventsListSchema",
    "RasdLatestImportSchema",
    "RecordAttendanceSchema",
    "RecordedAttendanceSchema",
    "RejectSchema",
    "ReportSchema",
    "ResetPinSchema",
    "ReverseEventSchema",
    "ReversedEventSchema",
    "ReviewResultsSchema",
    "RoleSetSchema",
    "RosterListSchema",
    "SaveThresholdsSchema",
    "SessionSchema",
    "SetActiveSchema",
    "SetRoleSchema",
    "StationSchema",
    "StationTaskSchema",
    "StudentsListSchema",
    "SubmitNoteSchema",
    "SubmitReadingSchema",
    "SubmitTahdirSchema",
    "SubmittedSchema",
    "TahdirReportSchema",
    "TeamsBoardSchema",
    "TeamsListSchema",
    "ThresholdsPreviewSchema",
    "ThresholdsSchema",
    "TodayQuestionSchema",
    "TransferMemberSchema",
    "TransferredMemberSchema",
    "UndoneAttendanceSchema",
    "UpdateQuestionSchema",
    "WeekPilotSchema",
    "WeekScoresSchema",
    "WeekTaskRefSchema",
    "WeightVersionIdSchema",
    "WeightsSchema",
]
