"""جدول طلبات القراءة وقيوده

Revision ID: 3c0fdc962416
Revises: 75f3cbd7db7e
Create Date: 2026-08-31 16:39:22.376936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0fdc962416'
down_revision = '75f3cbd7db7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_on', sa.Date(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('point_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'approved' AND point_event_id IS NOT NULL) OR (status <> 'approved' AND point_event_id IS NULL)", name='reading_approved_has_event'),
    sa.CheckConstraint("status <> 'rejected' OR review_reason IS NOT NULL", name='reading_rejected_has_reason'),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='reading_status_valid'),
    sa.CheckConstraint('pages > 0', name='reading_pages_positive'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['point_event_id'], ['point_events.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'read_on', 'book_title', name='uq_reading_per_day')
    )
    with op.batch_alter_table('reading_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_reading_pending', ['org_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
        batch_op.create_index('ix_reading_user', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_user')
        batch_op.drop_index('ix_reading_pending', postgresql_where=sa.text("status = 'pending'"))

    op.drop_table('reading_submissions')
    # ### end Alembic commands ###
