"""المخطط الأساسي: المنظمات والطلاب والأسراب وسجلّ الأحداث

Revision ID: 75f3cbd7db7e
Revises: 
Create Date: 2026-08-30 22:36:06.329751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f3cbd7db7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('week_starts_on', sa.SmallInteger(), nullable=False),
    sa.Column('grounded_after_days', sa.SmallInteger(), nullable=False),
    sa.Column('tank_capacity_l', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_lookup', ['org_id', 'student_no', 'at'], unique=False)

    op.create_table('rank_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('at_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_rank_key'),
    sa.UniqueConstraint('org_id', 'tier', name='uq_rank_tier')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('thread_color', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_team_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('student_no', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'student_no', name='uq_user_student_no')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_membership_team_active', ['team_id'], unique=False, postgresql_where=sa.text('left_at IS NULL'))
        batch_op.create_index('uq_membership_active', ['user_id'], unique=True, postgresql_where=sa.text('left_at IS NULL'))

    op.create_table('point_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'individual' AND user_id IS NOT NULL AND team_id IS NULL AND currency = 'hours') OR (scope = 'team' AND team_id IS NOT NULL AND user_id IS NULL AND currency = 'fuel')", name='currency_scope_match'),
    sa.CheckConstraint("currency IN ('hours','fuel')", name='currency_valid'),
    sa.CheckConstraint("kind <> 'correction' OR reason IS NOT NULL", name='correction_needs_reason'),
    sa.CheckConstraint("scope IN ('individual','team')", name='scope_valid'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_team_time', ['org_id', 'team_id', 'occurred_at'], unique=False, postgresql_where=sa.text("scope = 'team'"))
        batch_op.create_index('ix_event_user_time', ['org_id', 'user_id', 'occurred_at'], unique=False, postgresql_where=sa.text("scope = 'individual'"))
        batch_op.create_index('uq_event_external_ref', ['org_id', 'external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'))

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_user', ['user_id'], unique=False)

    op.create_table('weight_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_multipliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['weight_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'grade', name='uq_mastery_grade')
    )
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('hours_per_unit', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['weight_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'activity_type', name='uq_weight_activity')
    )
    # ### end Alembic commands ###



    # ═══════════════════════════════════════════════════════════════════════
    # ث-٢ — point_events سجلّ إلحاق فقط.
    #
    # كانت هذه قاعدة مكتوبة في AGENTS.md بلا فرض تقني، وهو نقضٌ حرفيّ لـADR-002:
    # «كود التطبيق يُنسى ويُلتفّ عليه؛ القيد لا». طبّقنا المبدأ على العملات
    # ونسيناه على السجلّ نفسه، حتى كشفته بوابات Stage 4.
    #
    # وTRUNCATE لا يُطلق مشغّلات الصفوف — مُختبَرًا على PostgreSQL 16 لا مفترَضًا —
    # فـseed.py والاختبارات تعمل بلا تغيير. وليس ذلك التفافًا على الحماية:
    # TRUNCATE يحتاج قفلًا حصريًّا وصلاحية، ولا يقع عرَضًا في مسار تطبيقي.
    # ═══════════════════════════════════════════════════════════════════════
    op.execute("""
        CREATE OR REPLACE FUNCTION point_events_append_only() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION
            'point_events سجلّ إلحاق فقط: التصحيح حدث معاكس بسبب مكتوب';
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER point_events_no_mutation
          BEFORE UPDATE OR DELETE ON point_events
          FOR EACH ROW EXECUTE FUNCTION point_events_append_only();
    """)

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS point_events_no_mutation ON point_events;")
    op.execute("DROP FUNCTION IF EXISTS point_events_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    op.drop_table('mastery_multipliers')
    op.drop_table('weight_versions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_user')

    op.drop_table('sessions')
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.drop_index('uq_event_external_ref', postgresql_where=sa.text('external_ref IS NOT NULL'))
        batch_op.drop_index('ix_event_user_time', postgresql_where=sa.text("scope = 'individual'"))
        batch_op.drop_index('ix_event_team_time', postgresql_where=sa.text("scope = 'team'"))

    op.drop_table('point_events')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('uq_membership_active', postgresql_where=sa.text('left_at IS NULL'))
        batch_op.drop_index('ix_membership_team_active', postgresql_where=sa.text('left_at IS NULL'))

    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('rank_thresholds')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_lookup')

    op.drop_table('login_attempts')
    op.drop_table('orgs')
    # ### end Alembic commands ###
