"""answers.point_event_id وقيد ث-١٧

Revision ID: 8dd683cd29af
Revises: ff06d8af1d73
Create Date: 2026-09-04 03:43:59.620297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd683cd29af'
down_revision = 'ff06d8af1d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_answers_point_event_id', 'point_events', ['point_event_id'], ['id']
        )
        batch_op.create_check_constraint(
            'answers_correct_matches_point_event',
            '(correct = false AND point_event_id IS NULL) OR (correct = true AND point_event_id IS NOT NULL)',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint('answers_correct_matches_point_event', type_='check')
        batch_op.drop_constraint('fk_answers_point_event_id', type_='foreignkey')
        batch_op.drop_column('point_event_id')

    # ### end Alembic commands ###
