"""وزن اختيار طيّار الأسبوع — ساعات بتاريخ الأسبوع

Revision ID: 922a1b617a1f
Revises: f400bddce319
Create Date: 2026-09-28 13:36:36.687298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a1b617a1f'
down_revision = 'f400bddce319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_of_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_hours', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('point_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_pilot_of_week_point_event', 'point_events', ['point_event_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_of_week', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pilot_of_week_point_event', type_='foreignkey')
        batch_op.drop_column('point_event_id')
        batch_op.drop_column('bonus_hours')

    # ### end Alembic commands ###
