"""تحضير القراءة: activity_type على reading_submissions وث-١٨

Revision ID: 958d957c47f0
Revises: fba8d096bade
Create Date: 2026-09-07 16:21:17.669738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958d957c47f0'
down_revision = 'fba8d096bade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(), server_default='reading', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_reading_per_day'), type_='unique')
        batch_op.create_unique_constraint('uq_reading_per_day', ['user_id', 'read_on', 'book_title', 'activity_type'])
        batch_op.create_check_constraint('tahdir_sun_to_wed_only', "activity_type <> 'tahdir' OR EXTRACT(DOW FROM read_on) IN (0,1,2,3)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('tahdir_sun_to_wed_only', type_='check')
        batch_op.drop_constraint('uq_reading_per_day', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reading_per_day'), ['user_id', 'read_on', 'book_title'])
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
