"""وقودٌ أسبوعيّ: مسوّدة في جدولها ثم اعتماد واحد

ثلاثة جداول (`fuel_weeks` · `fuel_week_tasks` · `fuel_week_scores`) وعمودٌ
رابط على `fuel_assessments`.

**وق-٦٧ باقٍ:** `fuel_assessments.point_event_id` لم يُمَسّ ولم يصر يقبل العدم.
كان أقصرُ طريقٍ إلى المسوّدة أن يقبله — وذاك نقضٌ حرفيّ للقيد الذي وُجد لمنع
«تقييمٍ يبدو مكتملًا وهو فارغ». فالمسوّدة في جدولها، ووجودُ صفٍّ في
`fuel_assessments` يبقى معناه: اعتُمد ودخل الدفتر.

Revision ID: f400bddce319
Revises: 0c8055cbcdab
Create Date: 2026-09-28 09:01:52.352444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f400bddce319'
down_revision = '0c8055cbcdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'week_start', name='uq_fuel_week')
    )
    op.create_table('fuel_week_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['fuel_activities.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['fuel_weeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'activity_id', name='uq_fuel_week_task')
    )
    op.create_table('fuel_week_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('score_pct >= 0 AND score_pct <= 100', name='fuel_week_scores_score_range'),
    sa.ForeignKeyConstraint(['criterion_id'], ['fuel_criteria.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['fuel_week_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'criterion_id', name='uq_fuel_week_score')
    )
    with op.batch_alter_table('fuel_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_task_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_fuel_assessment_per_week_task', ['week_task_id'])
        batch_op.create_foreign_key(
            'fk_fuel_assessment_week_task', 'fuel_week_tasks', ['week_task_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fuel_assessment_week_task', type_='foreignkey')
        batch_op.drop_constraint('uq_fuel_assessment_per_week_task', type_='unique')
        batch_op.drop_column('week_task_id')

    op.drop_table('fuel_week_scores')
    op.drop_table('fuel_week_tasks')
    op.drop_table('fuel_weeks')
    # ### end Alembic commands ###
