"""توسيع ث-٧: الإدخال اليدوي يستلزم سببًا أيضًا

Revision ID: fba8d096bade
Revises: 8dd683cd29af
Create Date: 2026-09-05 23:51:46.891430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba8d096bade'
down_revision = '8dd683cd29af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('correction_needs_reason'), type_='check')
        batch_op.create_check_constraint('correction_or_manual_needs_reason', "kind NOT IN ('correction', 'manual') OR reason IS NOT NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_events', schema=None) as batch_op:
        batch_op.drop_constraint('correction_or_manual_needs_reason', type_='check')
        batch_op.create_check_constraint(batch_op.f('correction_needs_reason'), "kind::text <> 'correction'::text OR reason IS NOT NULL")

    # ### end Alembic commands ###
